# Site settings
title: In the trenches
email: ospatil@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    My random ramblings on technology.
baseurl: "/old-blog/" # the subpath of your site, e.g. /blog/
url: "https://ospatil.github.io" # the base hostname & protocol for your site
twitter_username: omkar_p
github_username: ospatil

# Build settings
markdown: kramdown

plugins: ["jemoji"]

theme: jekyll-theme-minimal
