# Site settings
title: In the trenches
email: ospatil@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    My random ramblings on technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ospatil.github.io/old-blog" # the base hostname & protocol for your site
twitter_username: omkar_p
github_username: ospatil

# Build settings
markdown: kramdown

gems: ["jemoji"]

theme: jekyll-theme-minimal
